### ISSUE TITLE
Open Source  to rebuild?

### ISSUE THREAD

**Issue by Panoru84** [Velleman/K2400-BrightDot-Clock#2]
Hello @velbn,
your project looks great.
I was wondering if it is possible to use your code for privte rebuilds using LED Rings and some ESP.

Are you still improving this project?

Thanks from Germany

**Comment by BrenuDev** [comment]
Hi @Panoru84 !
Thanks! 
Currently there's no plans to further develop this.
But you're welcome to create new things with it.
You can certainly use this for private rebuilds :)
